#!/bin/bash
rm libforthyd.a
COMPILER="gfortran"
COMP_FLAGS="-c -O3"
LINK_FLAGS="-O3"
LIBRARIES="-lblas -llapack"
PROGRAM_NAME="eigensplines.out"
###########################################
echo "____________________________________________________________"
echo "start compilation"
echo "host:" $HOST
echo "compiler:" $COMPILER
echo "comp flags:" $COMP_FLAGS
echo "link flags:" $LINK_FLAGS
echo "libraries:" $LIBRARIES
echo "program name:" $PROGRAM_NAME
echo "____________________________________________________________"
###########################################
#Compiler to .o files
echo "compiling to object files..."
$COMPILER $COMP_FLAGS bin/bspline.f90
$COMPILER $COMP_FLAGS bin/bsplvb.f
$COMPILER $COMP_FLAGS bin/bsplvb_cmplx.f
$COMPILER $COMP_FLAGS bin/dbspline.f90
$COMPILER $COMP_FLAGS bin/dbsplvb.f90
$COMPILER $COMP_FLAGS bin/getsplines.f90
$COMPILER $COMP_FLAGS bin/getdsplines.f90
$COMPILER $COMP_FLAGS bin/gauleg.f
$COMPILER $COMP_FLAGS bin/ones.f90
$COMPILER $COMP_FLAGS bin/zeroes.f90
$COMPILER $COMP_FLAGS bin/wbmatrix.f90
$COMPILER $COMP_FLAGS bin/wbmatrixd.f90
$COMPILER $COMP_FLAGS bin/dbspline.f90
$COMPILER $COMP_FLAGS bin/glquad.f90
$COMPILER $COMP_FLAGS bin/integrate.f90
$COMPILER $COMP_FLAGS bin/legendrep.f90
$COMPILER $COMP_FLAGS bin/isinf.f90
$COMPILER $COMP_FLAGS bin/splineends.f90
$COMPILER $COMP_FLAGS bin/getbsplvbindex.f90
$COMPILER $COMP_FLAGS bin/getbsplineindex.f90
$COMPILER $COMP_FLAGS bin/qsort.f90
$COMPILER $COMP_FLAGS bin/summarizearray.f90
$COMPILER $COMP_FLAGS bin/get_bsplines.f90
$COMPILER $COMP_FLAGS bin/get_dbsplines.f90

echo "done"
echo "____________________________________________________________"
#
ar rsv libforthyd.a *.o
rm *.o
echo "done"
echo "____________________________________________________________"
#
echo "compiling main and linking..."
echo "done"
$COMPILER eigensplines.f90 -L./ -lforthyd $LIBRARIES -o $PROGRAM_NAME $LINK_FLAGS
#
echo "Compilation of" $PROGRAM_NAME "finished"
echo "Size of program:"
size $PROGRAM_NAME
echo "____________________________________________________________"
echo
