#!/bin/bash
rm libforttut.a
COMPILER="gfortran"
COMP_FLAGS="-c -fcheck=all"
LINK_FLAGS="-fcheck=all"
LIBRARIES="-lblas -llapack"
PROGRAM_NAME="eigensplines.out"
###########################################
echo "____________________________________________________________"
echo "start compilation"
echo "host:" $HOST
echo "compiler:" $COMPILER
echo "comp flags:" $COMP_FLAGS
echo "link flags:" $LINK_FLAGS
echo "libraries:" $LIBRARIES
echo "program name:" $PROGRAM_NAME
echo "____________________________________________________________"
###########################################
#Compiler to .o files
echo "compiling to object files with -fcheck=all..."
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/bspline.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/bsplvb.f
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/bsplvb_cmplx.f
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/dbspline.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/dbsplvb.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/getsplines.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/getdsplines.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/gauleg.f
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/ones.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/zeroes.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/wbmatrix.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/wbmatrixd.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/dbspline.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/glquad.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/integrate.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/legendrep.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/isinf.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/splineends.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/getbsplvbindex.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/frstinstind.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/getbsplineindex.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/qsort.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/summarizearray.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/get_bsplines.f90
$COMPILER $COMP_FLAGS ~/Documents/FortranPrograms/get_dbsplines.f90
echo "done"
echo "____________________________________________________________"
#
ar rsv libforttut.a *.o
rm *.o
echo "done"
echo "____________________________________________________________"
#
echo "compiling main and linking with -fcheck=all..."
echo "done"
#$COMPILER eigensplines.f90 -L./ -lforttut $LIBRARIES -o $PROGRAM_NAME -fcheck=all
$COMPILER eigensplines.f90 -L./ -lforttut $LIBRARIES -o $PROGRAM_NAME $LINK_FLAGS
#
echo "Compilation of" $PROGRAM_NAME "finished"
echo "Size of program:"
size $PROGRAM_NAME
echo "____________________________________________________________"
echo
