#!/bin/bash
rm libforthyd.a
COMPILER="gfortran"
COMP_FLAGS="-c -O3"
LINK_FLAGS="-O3"
LIBRARIES="-lblas -llapack"
PROGRAM_NAME="eigensplines.out"
###########################################
echo "____________________________________________________________"
echo "start compilation"
echo "host:" $HOST
echo "compiler:" $COMPILER
echo "comp flags:" $COMP_FLAGS
echo "link flags:" $LINK_FLAGS
echo "libraries:" $LIBRARIES
echo "program name:" $PROGRAM_NAME
echo "____________________________________________________________"
###########################################
#Compiler to .o files
echo "compiling to object files..."
$COMPILER $COMP_FLAGS src/bspline.f90
$COMPILER $COMP_FLAGS src/bsplvb.f
$COMPILER $COMP_FLAGS src/bsplvb_cmplx.f
$COMPILER $COMP_FLAGS src/dbspline.f90
$COMPILER $COMP_FLAGS src/dbsplvb.f90
$COMPILER $COMP_FLAGS src/getsplines.f90
$COMPILER $COMP_FLAGS src/getdsplines.f90
$COMPILER $COMP_FLAGS src/gauleg.f
$COMPILER $COMP_FLAGS src/ones.f90
$COMPILER $COMP_FLAGS src/zeroes.f90
$COMPILER $COMP_FLAGS src/wbmatrix.f90
$COMPILER $COMP_FLAGS src/wbmatrixd.f90
$COMPILER $COMP_FLAGS src/dbspline.f90
$COMPILER $COMP_FLAGS src/glquad.f90
$COMPILER $COMP_FLAGS src/integrate.f90
$COMPILER $COMP_FLAGS src/legendrep.f90
$COMPILER $COMP_FLAGS src/isinf.f90
$COMPILER $COMP_FLAGS src/splineends.f90
$COMPILER $COMP_FLAGS src/getbsplvsrcdex.f90
$COMPILER $COMP_FLAGS src/getbsplineindex.f90
$COMPILER $COMP_FLAGS src/qsort.f90
$COMPILER $COMP_FLAGS src/summarizearray.f90
$COMPILER $COMP_FLAGS src/get_bsplines.f90
$COMPILER $COMP_FLAGS src/get_dbsplines.f90

echo "done"
echo "____________________________________________________________"
#
ar rsv libforthyd.a *.o
rm *.o
echo "done"
echo "____________________________________________________________"
#
echo "compiling main and linking..."
echo "done"
$COMPILER eigensplines.f90 -L./ -lforthyd $LIBRARIES -o $PROGRAM_NAME $LINK_FLAGS
#
echo "Compilation of" $PROGRAM_NAME "finished"
echo "Size of program:"
size $PROGRAM_NAME
echo "____________________________________________________________"
echo
